name       : calendarsupport
version    : 19.08.1
release    : 26
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/calendarsupport-19.08.1.tar.xz : 74d1b19a924f2aad7f5a034a7e3b11f2ed5bb94cd21458f0255a64ac6163de97
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.libray
summary    : Calendar Support library provides helper utilities for calendaring applications
description: |
    Calendar Support library provides helper utilities for calendaring applications.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Quick)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdepim-apps-libs-devel
    - kguiaddons-devel
    - kholidays-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - kpimtextedit-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
