name       : calendarsupport
version    : 20.08.3
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/calendarsupport-20.08.3.tar.xz : 6d17138c8caca9ffa0a4f90f3841b10e2a5d7cbc005a408876c49c428e358027
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.libray
summary    : Calendar Support library provides helper utilities for calendaring applications
description: |
    Calendar Support library provides helper utilities for calendaring applications.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Quick)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - extra-cmake-modules
    - kcalutils-devel
    - kcodecs-devel
    - kcontacts-devel
    - kguiaddons-devel
    - kholidays-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - kpimtextedit-devel
    - kwindowsystem-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %patch -p1 -i $pkgfiles/port-away-from-depracted.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
