name       : calendarsupport
version    : 17.08.3
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/calendarsupport-17.08.3.tar.xz : b063ef5d9a0fcdc0dff5a7e9cfe9d058bfdea63c21c624de8f79ea29058123c6
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.libray
summary    : Calendar Support library provides helper utilities for calendaring applications.
description: |
    Calendar Support library provides helper utilities for calendaring applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Quick)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdelibs4support-devel
    - kdepim-apps-libs-devel
    - kholidays-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitemmodels-devel
    - kmime-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
