name       : calendarsupport
version    : 18.04.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/calendarsupport-18.04.0.tar.xz : 99b05699b4aa6635b2f014a420560a20da865a47652c83aa43ad9c26f1baa141
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.libray
optimize   : lto
summary    : Calendar Support library provides helper utilities for calendaring applications.
description: |
    Calendar Support library provides helper utilities for calendaring applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Quick)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdepim-apps-libs-devel
    - kguiaddons-devel
    - kholidays-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
