name       : calendarsupport
version    : 20.04.3
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/calendarsupport-20.04.3.tar.xz : 40b069e1561fac49f46dd0504af0ac459010ac98f30748b8f15a50ca1fd35b5b
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.libray
summary    : Calendar Support library provides helper utilities for calendaring applications
description: |
    Calendar Support library provides helper utilities for calendaring applications.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Quick)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalutils-devel
    - kcodecs-devel
    - kcontacts-devel
    - kdepim-apps-libs-devel
    - kguiaddons-devel
    - kholidays-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - kpimtextedit-devel
    - kwindowsystem-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
