name       : calendarsupport
version    : 17.08.1
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/calendarsupport-17.08.1.tar.xz : 5b10f7e78950af32cf6e07c264c235ef3f239bb92e26503fa7421224ac2e3adc
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.libray
summary    : Calendar Support library provides helper utilities for calendaring applications.
description: |
    Calendar Support library provides helper utilities for calendaring applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Quick)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdelibs4support-devel
    - kdepim-apps-libs-devel
    - kholidays-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitemmodels-devel
    - kmime-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
