name       : calendarsupport
version    : 22.08.3
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/calendarsupport-22.08.3.tar.xz : 1dd898ec8709b63cd27383bbf3ae0ae7b1272b4cdaab726c914a77f0cad2bed2
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.libray
summary    : Calendar Support library provides helper utilities for calendaring applications
description: |
    Calendar Support library provides helper utilities for calendaring applications.
builddeps  :
    - pkgconfig(Qt5Quick)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
    - kguiaddons-devel
    - kholidays-devel
    - kidentitymanagement-devel
    - kio-devel
    - kpimtextedit-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
