name       : calendarsupport
version    : 22.12.1
release    : 65
source     :
    - https://cdn.download.kde.org/stable/release-service/22.12.1/src/calendarsupport-22.12.1.tar.xz : 63a9d60b10a02454853339439f5a32a3f8f9c91a25cdb3cf6a892989692de9fb
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.libray
summary    : Calendar Support library provides helper utilities for calendaring applications
description: |
    Calendar Support library provides helper utilities for calendaring applications.
builddeps  :
    - pkgconfig(Qt5Quick)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
    - kguiaddons-devel
    - kholidays-devel
    - kidentitymanagement-devel
    - kio-devel
    - kpimtextedit-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
