name       : calendarsupport
version    : 21.04.1
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/calendarsupport-21.04.1.tar.xz : bdff263d1b4d07ec54817f0ad4529481a9554d3cba86813069880e02f7697fe9
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.libray
summary    : Calendar Support library provides helper utilities for calendaring applications
description: |
    Calendar Support library provides helper utilities for calendaring applications.
builddeps  :
    - pkgconfig(Qt5Quick)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
    - kguiaddons-devel
    - kholidays-devel
    - kidentitymanagement-devel
    - kio-devel
    - kpimtextedit-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
