name       : calendarsupport
version    : 21.08.1
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/calendarsupport-21.08.1.tar.xz : 7c6d2dc1300c232cce4d375e4619bbef228c471a2bd91c1e188530ff1a5f3559
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.libray
summary    : Calendar Support library provides helper utilities for calendaring applications
description: |
    Calendar Support library provides helper utilities for calendaring applications.
builddeps  :
    - pkgconfig(Qt5Quick)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
    - kguiaddons-devel
    - kholidays-devel
    - kidentitymanagement-devel
    - kio-devel
    - kpimtextedit-devel
    - libkdepim-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
